package com.sainiharika.enterpriseai.communication.service.impl;

import com.sainiharika.enterpriseai.common.ai.model.PromptDefinition;
import com.sainiharika.enterpriseai.common.ai.prompt.PromptTemplateEngine;
import com.sainiharika.enterpriseai.common.ai.provider.AIProvider;
import com.sainiharika.enterpriseai.common.ai.provider.AIProviderType;
import com.sainiharika.enterpriseai.common.ai.provider.factory.AIProviderFactory;
import com.sainiharika.enterpriseai.communication.dto.GenerateCommunicationRequest;
import com.sainiharika.enterpriseai.communication.dto.GenerateCommunicationResponse;
import com.sainiharika.enterpriseai.communication.prompt.CommunicationPromptStrategy;
import com.sainiharika.enterpriseai.communication.prompt.factory.CommunicationPromptStrategyFactory;
import com.sainiharika.enterpriseai.communication.service.CommunicationService;
import lombok.AllArgsConstructor;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.stereotype.Service;

@AllArgsConstructor
@Service
public class CommunicationServiceImpl implements CommunicationService {

    private final CommunicationPromptStrategyFactory factory;

    private final AIProviderFactory aiProviderFactory;

    @Override
    public GenerateCommunicationResponse generateEmail(GenerateCommunicationRequest request) {

        CommunicationPromptStrategy promptStrategy = factory.getStrategy(request.getCommunicationType());
        PromptDefinition promptDefinition = promptStrategy.buildPrompt(request);

        AIProvider aiProvider = aiProviderFactory.getProvider(AIProviderType.OLLAMA_PROVIDER);

        String response = aiProvider.generate(promptDefinition);


        return GenerateCommunicationResponse.builder()
                .subject(request.getSubject())
                .body(response)
                .signature("Generated by Enterprise AI Services")
                .build();
    }
}
